# Módulo 3 - Desafio 2
## Estadística descriptiva y probabilidades (parte 2)

En este documento realizaremos una revisión sobre los resultados del Mundial de futbol 2014.

In [2]:
# Cargamos los datos
import pandas as pd

df_worldcup = pd.read_csv('worldcup2014.csv')
df_worldcup.head()

,team,continent,group,group_pos,cantidad_juegos,juegos_ganados,juegos_empatados,juegos_perdidos,goles_favor,goles_contra,goles_diferencia,puntos,clasificado
0,Brazil,southamerica,A,1,3,2,1,0,7,2,5,7,1
1,Mexico,northamerica,A,2,3,2,1,0,4,1,3,7,1
2,Croatia,europe,A,3,3,1,0,2,6,6,0,3,0
3,Cameroon,africa,A,4,3,0,0,3,1,9,−8,0,0
4,Netherlands,europe,B,1,3,3,0,0,10,3,7,9,1

### Pregunta 1
Considerando el experimento de seleccionar un país participante al azar, se pide
determinar las probabilidades de los siguientes sucesos:

In [ ]:
print("Pertenecer a África: ", df_worldcup['continent'].value_counts(normalize=True)['africa'])
print("Pertenecer a Asia: ", df_worldcup['continent'].value_counts(normalize=True)['asia'])
print("Pertenecer a Europa: ", df_worldcup['continent'].value_counts(normalize=True)['europe'])
print("Pertenecer a Norteamérica: ", df_worldcup['continent'].value_counts(normalize=True)['northamerica'])
print("Pertenecer a Sudamérica: ", df_worldcup['continent'].value_counts(normalize=True)['southamerica'])

Pertenecer a África:  0.15625
Pertenecer a Asia:  0.125
Pertenecer a Europa:  0.40625
Pertenecer a Norteamérica:  0.125
Pertenecer a Sudamérica:  0.1875

In [ ]:
total = df_worldcup.shape[0]  # guardamos el total de filas
print("Clasificar a segunda ronda: ", df_worldcup[df_worldcup['clasificado'] == 1].shape[0] / total)
print("Ganar al menos un partido: ", df_worldcup[df_worldcup['juegos_ganados'] >= 1].shape[0] / total)

Clasificar a segunda ronda:  0.5
Ganar al menos un partido:  0.71875

    juegos_ganados  clasificado
0                2            1
1                2            1
2                1            0
3                0            0
4                3            1
5                2            1
6                1            0
7                0            0
8                3            1
9                1            1
10               1            0
11               0            0
12               2            1
13               2            1
14               1            0
15               0            0
16               2            1
17               2            1
18               1            0
19               0            0
20               3            1
21               1            1
22               1            0
23               0            0
24               2            1
25               1            1
26               1            0
27               0            0
28               3            1
29               1            1
30               0            0
31               0            0