# Módulo 3 - Desafío 1
## Estadística descriptiva y probabilidades (parte 1)

En este documento realizaremos un análisis estadístico descriptivo de un dataset que contiene información salarial,
por ejemplo, el salario, el cargo, y el tamaño de la compañia de una persona.

In [1]:
import pandas as pd

# Carga inicial de datos
df_salaries = pd.read_csv("ds_salaries.csv")
df_salaries.head()

,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
0,2023,SE,FT,Principal Data Scientist,80000,EUR,85847,ES,100,ES,L
1,2023,MI,CT,ML Engineer,30000,USD,30000,US,100,US,S
2,2023,MI,CT,ML Engineer,25500,USD,25500,US,100,US,S
3,2023,SE,FT,Data Scientist,175000,USD,175000,CA,100,CA,M
4,2023,SE,FT,Data Scientist,120000,USD,120000,CA,100,CA,M

### Pregunta 1
El promedio general de los salarios, desviación estándar, quintiles y rango. (hint: escoge la columna adecuada para comparar)

In [2]:
# Obtendremos esta información a partir de la columna de salarios en dólares

salaries = df_salaries["salary_in_usd"]
mean_usd = salaries.mean()
std = salaries.std()
q1 = salaries.quantile(0.2)
q2 = salaries.quantile(0.4)
q3 = salaries.quantile(0.6)
q4 = salaries.quantile(0.8)
q5 = salaries.quantile(1)
disp_range = salaries.max() - salaries.min()

print("Promedio en USD: ", mean_usd)
print("Desviación estandar: ", std)
print("Percentil 0: ", salaries.min())
print("Percentil 20: ", q1)
print("Percentil 40: ", q2)
print("Percentil 60: ", q3)
print("Percentil 80: ", q4)
print("Percentil 100: ", salaries.max())
print("Rango dispersion: ", disp_range)

Promedio en USD:  137570.38988015978
Desviación estandar:  63055.625278224084
Percentil 0:  5132
Percentil 20:  83972.8
Percentil 40:  120000.0
Percentil 60:  149850.0
Percentil 80:  185900.0
Percentil 100:  450000
Rango dispersion:  444868

### Pregunta 2.- 
Una comparación entre los salarios agrupados por 3 diferentes categorías a tu elección. ¿Para cuál de ellas las medidas de tendencia central son más representativas? ¿Para cuál son menos representativas? Explica

##### Primera categoría: Tipo de empleo.

In [3]:
group_by_type = df_salaries.groupby("employment_type")["salary_in_usd"].agg(["mean", "median", "std", "count"])
display(group_by_type)

                          mean    median            std  count
employment_type
CT               113446.900000   75000.0  130176.746842     10
FL                51807.800000   50000.0   29458.879336     10
FT               138314.199570  135000.0   62452.177613   3718
PT                39533.705882   21669.0   38312.145181     17

#### Segunda categoría: Ratio de trabajo remoto

In [4]:
group_by_ratio = df_salaries.groupby("remote_ratio")["salary_in_usd"].agg(["mean", "median", "std", "count"])
display(group_by_ratio)

                       mean    median           std  count
remote_ratio
0             144316.202288  139600.0  59799.970864   1923
50             78400.687831   63312.0  61326.133522    189
100           136481.452830  135000.0  63373.507699   1643

#### Tercera categoría: Tamaño de compañía

In [5]:
group_by_company_size = df_salaries.groupby("company_size")["salary_in_usd"].agg(["mean", "median", "std", "count"])
display(group_by_company_size)

                       mean    median           std  count
company_size
L             118300.982379  108500.0  75832.391505    454
M             143130.548367  140000.0  58992.813382   3153
S              78226.682432   62146.0  61955.141792    148

#### Análisis
Para ello, primero definimos qué significa que las medidas de tendencia central sean o no más representativas.
Si tanto el promedio como su mediana tienen valores similares, y la desviación estándar es baja con respecto al promedio, podemos decir que estas médidas son más representativas de los datos. Es decir, los datos se encuentran más cercas unos de otros en promedio

Entonces:

- Para los tipos de empleo, las medidas de tendencia central en las categorias de freelance (FL) y full time (FT) son más representativas, mientras que en las categorías de contrato (CT) y part time (PT) no lo son.
- En el caso de el ratio de trabajo remoto, las medidas de tendencia central son muy representativas en el caso de trabajo 100% remoto, medianamente representativas para modalidad presencial (0%), y poco representativas para trabajos con modalidad híbrida.
- Por último, las medidas de tendencia central respecto al tamaño de la compañía son más representativas tanto en compañías grandes (L) como medianas (M), mientras que son poco representativas para compañías pequeñas (S).

### Pregunta 3
¿Qué cargos reciben mejores sueldos en las empresas con sede en Estados Unidos? 

Para ello, primero filtramos por trabajos cuyas empresas se encuentran en US.
Luego, agrupamos por el título del cargo, y calculamos el promedio, la mediana y el max del salario en dolares de estos grupos.
Para este conjunto de datos, los cargos mejor pagados son:
- Data analytics lead
- Data science tech lead
- Director of data science

In [6]:

df_salaries_us = df_salaries[df_salaries["company_location"] == "US"]

df_salaries_by_job_title = df_salaries_us.groupby("job_title")
df_salaries_us_by_job_title = df_salaries_by_job_title["salary_in_usd"].agg(
    mean='mean',
    median='median',
    max='max',
    count='count'
).sort_values(by="mean", ascending=False)

display(df_salaries_us_by_job_title.head(10))

                                             mean    median     max  count
job_title
Data Analytics Lead                 405000.000000  405000.0  405000      1
Data Science Tech Lead              375000.000000  375000.0  375000      1
Director of Data Science            294375.000000  287500.0  353200      4
Principal Data Scientist            255500.000000  227500.0  416000      4
Cloud Data Architect                250000.000000  250000.0  250000      1
Applied Data Scientist              238000.000000  177000.0  380000      3
Head of Data                        233183.333333  220000.0  329500      6
Machine Learning Software Engineer  217400.000000  180000.0  375000      5
Data Lead                           212500.000000  212500.0  225000      2
Head of Data Science                202355.000000  195800.0  314100      5